import Header from "@/components/Header";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Amplify",
  description: "Generated by create next app, Amplify Test",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <Header />
        <div className="mt-20 h-[calc(100vh-80px)] max-w-[1224px] w-full mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
